# Use a Go 1.21 or newer image
FROM golang:1.22

# Install Delve
RUN go install github.com/go-delve/delve/cmd/dlv@latest

# Set the working directory inside the container
WORKDIR /app

# Copy the Go application into the container
COPY . .

# Expose the port Delve will use (default is 2345)
EXPOSE 2345
COPY entrypoint.sh .

# Start Delve in headless mode to listen for remote connections
ENTRYPOINT [ "/bin/sh", "entrypoint.sh" ]
